name: Deploy stage

on:
  workflow_call:
    inputs:
      country:
        required: true
        type: string
      deploy_env:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy (${{ inputs.country }}/${{ inputs.deploy_env }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    environment:
      name: ${{ inputs.country }}-${{ inputs.deploy_env }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ansible
      - name: Deploy the requested image version
        env:
          ANSIBLE_FORCE_COLOR: "true"
          PY_COLORS: "1"
          ANSIBLE_CONFIG: .github/ansible/ansible.cfg
          DEPLOY_COUNTRY: ${{ inputs.country }}
          DEPLOY_ENV: ${{ inputs.deploy_env }}
          IMAGE_VERSION: ${{ inputs.image_version }}
          GITHUB_TOKEN: ${{ github.token }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: ansible-playbook .github/ansible/playbooks/deploy.yml
