name: North America pipeline

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  delivery:
    uses: ./.github/workflows/pipeline-common.yml
    with:
      country: na
      deploy_env: ${{ inputs.deploy_env }}
      image_version: ${{ inputs.image_version }}
    secrets: inherit
