name: Route regional pipeline

on:
  workflow_call:
    inputs:
      country:
        required: true
        type: string
      deploy_env:
        required: true
        type: string
      image_version:
        required: true
        type: string

jobs:
  kr:
    if: ${{ inputs.country == 'kr' }}
    uses: ./.github/workflows/pipeline-kr.yml
    with:
      deploy_env: ${{ inputs.deploy_env }}
      image_version: ${{ inputs.image_version }}
    secrets: inherit

  eu:
    if: ${{ inputs.country == 'eu' }}
    uses: ./.github/workflows/pipeline-eu.yml
    with:
      deploy_env: ${{ inputs.deploy_env }}
      image_version: ${{ inputs.image_version }}
    secrets: inherit

  na:
    if: ${{ inputs.country == 'na' }}
    uses: ./.github/workflows/pipeline-na.yml
    with:
      deploy_env: ${{ inputs.deploy_env }}
      image_version: ${{ inputs.image_version }}
    secrets: inherit
