name: Test stage

on:
  workflow_call:
    inputs:
      country:
        required: true
        type: string
      deploy_env:
        required: true
        type: string
      runtime_image:
        required: true
        type: string

jobs:
  test:
    name: Test (${{ inputs.country }}/${{ inputs.deploy_env }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ${{ inputs.runtime_image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    env:
      ANSIBLE_FORCE_COLOR: "true"
      PY_COLORS: "1"
      ANSIBLE_CONFIG: .github/ansible/ansible.cfg
      DEPLOY_COUNTRY: ${{ inputs.country }}
      DEPLOY_ENV: ${{ inputs.deploy_env }}
    steps:
      - uses: actions/checkout@v4
      - name: Run configured tests
        run: ansible-playbook .github/ansible/playbooks/test.yml
