all:
  vars:
    ansible_user: deploy
    ansible_port: 22
  children:
    north_america:
      children:
        north_america_validation:
        north_america_production:
    europe:
      children:
        europe_validation:
        europe_production:
    domestic:
      children:
        domestic_validation:
        domestic_production:
    validation:
      children:
        north_america_validation:
        europe_validation:
        domestic_validation:
    production:
      children:
        north_america_production:
        europe_production:
        domestic_production:
    north_america_validation:
      hosts:
        na-validation-app-1:
          ansible_host: na-validation-app-1.example.internal
    north_america_production:
      hosts:
        na-production-app-1:
          ansible_host: na-production-app-1.example.internal
        na-production-app-2:
          ansible_host: na-production-app-2.example.internal
    europe_validation:
      hosts:
        eu-validation-app-1:
          ansible_host: eu-validation-app-1.example.internal
    europe_production:
      hosts:
        eu-production-app-1:
          ansible_host: eu-production-app-1.example.internal
        eu-production-app-2:
          ansible_host: eu-production-app-2.example.internal
    domestic_validation:
      hosts:
        kr-validation-app-1:
          ansible_host: kr-validation-app-1.example.internal
    domestic_production:
      hosts:
        kr-production-app-1:
          ansible_host: kr-production-app-1.example.internal
        kr-production-app-2:
          ansible_host: kr-production-app-2.example.internal

