---
build:
  arguments:
    REGION_PARAMETER: KR

deploy:
  spring_profile: "kr,prd"
  restart_policy: always
  stabilize_seconds: 15
  cleanup:
    remove_previous_image: true
    prune_dangling_images: true
  environment:
    APP_RUNTIME_MODE: production
    LOG_LEVEL: INFO
    TZ: Asia/Seoul
    APP_REGION: kr
    APP_BASE_URL: https://kr.example.com
  volumes:
    - /var/log/delivery-template-kr-prd:/app/log
  targets:
    - name: app-1
      port_mapping: "8080:8080"
      environment:
        APM_TARGET_NAME: DELIVERY_TEMPLATE_KR_PRD_01
      volumes: []
