---
build:
  arguments:
    REGION_PARAMETER: KR

deploy:
  spring_profile: "kr,stg"
  restart_policy: unless-stopped
  stabilize_seconds: 0
  cleanup:
    remove_previous_image: true
    prune_dangling_images: false
  environment:
    APP_RUNTIME_MODE: verification
    LOG_LEVEL: DEBUG
    TZ: Asia/Seoul
    APP_REGION: kr
    APP_BASE_URL: https://stg-kr.example.com
  volumes:
    - /var/log/delivery-template-kr-stg:/app/log
  targets:
    - name: app-1
      port_mapping: "18080:8080"
      environment:
        APM_TARGET_NAME: DELIVERY_TEMPLATE_KR_STG_01
      volumes: []
