---
build:
  arguments:
    REGION_PARAMETER: EU

deploy:
  spring_profile: "eu,prd"
  restart_policy: always
  stabilize_seconds: 15
  cleanup:
    remove_previous_image: true
    prune_dangling_images: true
  environment:
    APP_RUNTIME_MODE: production
    LOG_LEVEL: INFO
    TZ: Europe/Berlin
    APP_REGION: eu
    APP_BASE_URL: https://eu.example.com
  volumes:
    - /var/log/delivery-template-eu-prd:/app/log
  targets:
    - name: app-1
      port_mapping: "8081:8080"
      environment:
        APM_TARGET_NAME: DELIVERY_TEMPLATE_EU_PRD_01
      volumes: []
