---
build:
  arguments:
    REGION_PARAMETER: NA

deploy:
  spring_profile: "na,prd"
  restart_policy: always
  stabilize_seconds: 15
  cleanup:
    remove_previous_image: true
    prune_dangling_images: true
  environment:
    APP_RUNTIME_MODE: production
    LOG_LEVEL: INFO
    TZ: America/Toronto
    APP_REGION: na
    APP_BASE_URL: https://na.example.com
  volumes:
    - /var/log/delivery-template-na-prd:/app/log
  targets:
    - name: app-1
      port_mapping: "8082:8080"
      environment:
        APM_TARGET_NAME: DELIVERY_TEMPLATE_NA_PRD_01
      volumes: []
