---
build:
  arguments:
    REGION_PARAMETER: NA

deploy:
  spring_profile: "na,stg"
  restart_policy: unless-stopped
  stabilize_seconds: 0
  cleanup:
    remove_previous_image: true
    prune_dangling_images: false
  environment:
    APP_RUNTIME_MODE: verification
    LOG_LEVEL: DEBUG
    TZ: America/Toronto
    APP_REGION: na
    APP_BASE_URL: https://stg-na.example.com
  volumes:
    - /var/log/delivery-template-na-stg:/app/log
  targets:
    - name: app-1
      port_mapping: "18082:8080"
      environment:
        APM_TARGET_NAME: DELIVERY_TEMPLATE_NA_STG_01
      volumes: []
