build_name: delivery-template-na-stg
region_param: NA
spring_profile: "na,stg"

docker_registry: ghcr.io
dockerfile: Dockerfile

target_servers:
  - name: na-stg-app-1
    host: na-stg-app-1.example.internal
    extra_env:
      APM_TARGET_NAME: DELIVERY_TEMPLATE_NA_STG_01

port_mapping: "18080:8080"
restart_policy: unless-stopped

extra_volumes:
  - /var/log/delivery-template:/app/log

extra_env:
  TZ: America/Toronto
  APP_REGION: na
  APP_BASE_URL: https://stg-na.example.com

health_check_port: 18080
health_check_path: /actuator/health
stabilize_seconds: 0
