spring.application.name=spring-batch-thread-efficiency
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

experiment.item-count=2000
experiment.chunk-size=400
experiment.partition-concurrency=4
experiment.processor-concurrency=400
experiment.io-delay=10ms
