target:
  group: na_prd
  name: na-prd
  deployment_root: /opt/delivery-template/na-prd
  host_port: 8080
  container_port: 80
  restart_policy: always
  healthcheck_path: /
  extra_volumes: []
  runtime_env: {}

release:
  app_name: delivery-template-app
  image_name: delivery-template-app
  dockerfile: Dockerfile
  build_args:
    REGION_PARAMETER: na
  runtime_env:
    TZ: America/Toronto
    APP_REGION: na
    APP_BASE_URL: https://na.example.com
    SPRING_PROFILES_ACTIVE: na,prd
