all:
  vars:
    ansible_user: deploy
    ansible_port: 22
  children:
    kr:
      children:
        kr_stg:
        kr_prd:
    eu:
      children:
        eu_stg:
        eu_prd:
    na:
      children:
        na_stg:
        na_prd:
    stg:
      children:
        kr_stg:
        eu_stg:
        na_stg:
    prd:
      children:
        kr_prd:
        eu_prd:
        na_prd:
    kr_stg:
      hosts:
        kr-stg-app-1:
          ansible_host: kr-stg-app-1.example.internal
    kr_prd:
      hosts:
        kr-prd-app-1:
          ansible_host: kr-prd-app-1.example.internal
        kr-prd-app-2:
          ansible_host: kr-prd-app-2.example.internal
    eu_stg:
      hosts:
        eu-stg-app-1:
          ansible_host: eu-stg-app-1.example.internal
    eu_prd:
      hosts:
        eu-prd-app-1:
          ansible_host: eu-prd-app-1.example.internal
        eu-prd-app-2:
          ansible_host: eu-prd-app-2.example.internal
    na_stg:
      hosts:
        na-stg-app-1:
          ansible_host: na-stg-app-1.example.internal
    na_prd:
      hosts:
        na-prd-app-1:
          ansible_host: na-prd-app-1.example.internal
        na-prd-app-2:
          ansible_host: na-prd-app-2.example.internal
