region_code: eu
container_timezone: Europe/Berlin
harbor_project: apps-eu

runtime_env_region:
  TZ: "{{ container_timezone }}"
  APP_REGION_NAME: europe
  DEFAULT_LOCALE: en-GB
  CDN_BASE_URL: https://cdn-eu.example.com

