target:
  group: eu_prd
  name: eu-prd
  deployment_root: /opt/delivery-template/eu-prd
  host_port: 8080
  container_port: 80
  restart_policy: always
  healthcheck_path: /
  extra_volumes: []
  runtime_env: {}

release:
  app_name: delivery-template-app
  image_name: delivery-template-app
  dockerfile: Dockerfile
  build_args:
    REGION_PARAMETER: eu
  runtime_env:
    TZ: Europe/Berlin
    APP_REGION: eu
    APP_BASE_URL: https://eu.example.com
    SPRING_PROFILES_ACTIVE: eu,prd
